sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t roronoazorroippo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true roronoazorroippo/docker-react npm run test
